## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Dropout

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_type = application_df['APPLICATION_TYPE'].value_counts()
app_type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
app_cutoff = 527
application_types_to_replace = app_type[app_type <= app_cutoff].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_types = application_df['CLASSIFICATION'].value_counts()
class_types

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_types_cleaned = class_types[class_types >1]
class_types_cleaned

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_cutoff = 1882
classifications_to_replace = class_types[class_types <= class_cutoff].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
categorical_data = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 
                    'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 
                    'SPECIAL_CONSIDERATIONS']
cleaned_df = pd.get_dummies(application_df, columns=categorical_data)

cleaned_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [11]:
# Split our preprocessed data into our features and target arrays
y = cleaned_df['IS_SUCCESSFUL']
X = cleaned_df.drop(columns=['IS_SUCCESSFUL'])

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=200, activation="relu", kernel_regularizer=regularizers.l2(0.01),input_dim=43))
nn_model.add(Dropout(0.5))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=100, activation="relu", kernel_regularizer=regularizers.l2(0.01)))
nn_model.add(Dropout(0.5))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 200)            │         8,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 200)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 100)            │        20,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29,001 (113.29 KB)

 Trainable params: 29,001 (113.29 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 420us/step - accuracy: 0.6864 - loss: 1.3938
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.7250 - loss: 0.6099
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.7250 - loss: 0.6005
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7219 - loss: 0.6008
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7232 - loss: 0.5956
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7238 - loss: 0.5954
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7256 - loss: 0.5911
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - accuracy: 0.7246 - loss: 0.5930
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7256 - loss: 0.5928
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7202 - loss: 0.5937
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7235 - loss: 0.5965
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.7266 - loss: 0.5897
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.7275 - loss: 0.5859
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7203 - loss: 0.5982
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7231 - loss: 0.5944
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7306 - loss: 0.5846
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.7210 - loss: 0.5949
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.7283 - loss: 0.5920
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.7211 - loss: 0.5936
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.7225 - loss: 0.5915
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7322 - loss: 0.5861
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7266 - loss: 0.5868
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7231 - loss: 0.5922
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7232 - loss: 0.5924
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7291 - loss: 0.5853
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.7222 - loss: 0.5919
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7202 - loss: 0.5913
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7241 - loss: 0.5889
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7253 - loss: 0.5872
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.7249 - loss: 0.5911
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7200 - loss: 0.5903
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7242 - loss: 0.5912
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7270 - loss: 0.5897
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7261 - loss: 0.5848
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7244 - loss: 0.5907
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.7253 - loss: 0.5882
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7206 - loss: 0.5884
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7156 - loss: 0.5953
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7288 - loss: 0.5819
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7272 - loss: 0.5858
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7237 - loss: 0.5889
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7176 - loss: 0.5930
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7255 - loss: 0.5900
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7191 - loss: 0.5891
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7277 - loss: 0.5818
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7244 - loss: 0.5860
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.7207 - loss: 0.5899
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.7254 - loss: 0.5859
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7247 - loss: 0.5880
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.7225 - loss: 0.5886
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.7291 - loss: 0.5837
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.7244 - loss: 0.5884
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.7236 - loss: 0.5873
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - accuracy: 0.7187 - loss: 0.5916
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7240 - loss: 0.5881
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7190 - loss: 0.5896
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.7248 - loss: 0.5860
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7252 - loss: 0.5857
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7219 - loss: 0.5905
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.7232 - loss: 0.5864
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.7288 - loss: 0.5839
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7260 - loss: 0.5855
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7229 - loss: 0.5895
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7249 - loss: 0.5886
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7249 - loss: 0.5850
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.7243 - loss: 0.5852
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7214 - loss: 0.5882
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7289 - loss: 0.5829
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.7264 - loss: 0.5863
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7258 - loss: 0.5835
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.7241 - loss: 0.5884
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.7182 - loss: 0.5914
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7261 - loss: 0.5853
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.7241 - loss: 0.5870
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.7254 - loss: 0.5867
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7215 - loss: 0.5896
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.7205 - loss: 0.5890
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7212 - loss: 0.5877
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.7218 - loss: 0.5866
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.7214 - loss: 0.5871
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7230 - loss: 0.5869
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.7261 - loss: 0.5853
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7218 - loss: 0.5870
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.7242 - loss: 0.5854
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.7212 - loss: 0.5917
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7244 - loss: 0.5843
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.7243 - loss: 0.5848
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.7231 - loss: 0.5846
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7249 - loss: 0.5882
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7240 - loss: 0.5840
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.7235 - loss: 0.5864
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.7174 - loss: 0.5913
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.7198 - loss: 0.5900
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7211 - loss: 0.5905
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.7248 - loss: 0.5843
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7208 - loss: 0.5873
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.7272 - loss: 0.5847
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7283 - loss: 0.5801
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7279 - loss: 0.5834
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7249 - loss: 0.5863

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 450us/step - accuracy: 0.7251 - loss: 0.5754
Loss: 0.5754404067993164, Accuracy: 0.7251312136650085

In [17]:
# Export our model to HDF5 file
nn_model.save('AlphabetSoupCharity_Optimization2.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.